'use client';

import Link from 'next/link';
import {
  Row,
  Col,
  Card,
  Tag,
  Typography,
  Space,
  Progress,
  List,
  Statistic,
  Breadcrumb,
  Table,
} from 'antd';
import {
  AimOutlined,
  CheckCircleFilled,
  RiseOutlined,
  BookOutlined,
  BulbOutlined,
} from '@ant-design/icons';
import { Header } from '@/components/shared/Header/Header';
import styles from './insights.module.scss';

const { Title, Text, Paragraph } = Typography;

const skillGapData = [
  {
    key: '1',
    skill: 'Next.js 15 App Router & SSR',
    proficiency: 'Master (98%)',
    demand: 'Very High',
    status: 'Ready',
  },
  {
    key: '2',
    skill: 'NestJS + SQLite / TypeORM',
    proficiency: 'Advanced (94%)',
    demand: 'High',
    status: 'Ready',
  },
  {
    key: '3',
    skill: 'Ant Design (v5) + SCSS Modules',
    proficiency: 'Master (96%)',
    demand: 'High',
    status: 'Ready',
  },
  {
    key: '4',
    skill: 'GraphQL / Apollo Federation',
    proficiency: 'Intermediate (72%)',
    demand: 'Medium',
    status: 'Recommended',
  },
  {
    key: '5',
    skill: 'Docker & Kubernetes Deployment',
    proficiency: 'Intermediate (68%)',
    demand: 'High',
    status: 'Recommended',
  },
];

export default function InsightsPage() {
  return (
    <div className={styles.pageContainer}>
      <Header />

      <div className={styles.contentWrapper}>
        <Breadcrumb
          items={[
            { title: <Link href="/">Dashboard</Link> },
            { title: 'AI Insights' },
          ]}
          className={styles.breadcrumbMargin}
        />

        <div className={styles.pageHeader}>
          <Title level={2} className={styles.pageTitle}>
            AI Career Intelligence & Market Analytics
          </Title>
          <Paragraph type="secondary">
            Personalized skill gap evaluation, salary benchmarks, and interview readiness insights generated by Hunter-AI Scout.
          </Paragraph>
        </div>

        {/* Top Summary Cards */}
        <Row gutter={[16, 16]} className={styles.summaryRow}>
          <Col xs={24} sm={8}>
            <Card hoverable className={styles.cardRounded}>
              <Statistic
                title="Market Position Score"
                value={96}
                suffix="/ 100"
                prefix={<RiseOutlined className={styles.iconSuccess} />}
              />
              <Text type="secondary" className={styles.statSubtext}>
                Top 4% profile match for Full Stack roles
              </Text>
            </Card>
          </Col>

          <Col xs={24} sm={8}>
            <Card hoverable className={styles.cardRounded}>
              <Statistic
                title="Estimated Market Value"
                value={165000}
                prefix={<Text strong className={styles.dollarPrefix}>$</Text>}
                suffix="/ yr"
              />
              <Text type="secondary" className={styles.statSubtext}>
                Based on 140+ remote Next.js/NestJS listings
              </Text>
            </Card>
          </Col>

          <Col xs={24} sm={8}>
            <Card hoverable className={styles.cardRounded}>
              <Statistic
                title="Interview Readiness"
                value={92}
                suffix="%"
                prefix={<CheckCircleFilled className={styles.iconPurple} />}
              />
              <Progress percent={92} showInfo={false} strokeColor="#8b5cf6" size="small" className={styles.statProgress} />
            </Card>
          </Col>
        </Row>

        <Row gutter={[24, 24]}>
          {/* Skill Gap Analysis Table */}
          <Col xs={24} lg={16}>
            <Card
              title={
                <Space>
                  <AimOutlined className={styles.iconPrimary} />
                  <span>Tech Stack Proficiency & Market Demand</span>
                </Space>
              }
              className={styles.cardRounded}
            >
              <Table
                dataSource={skillGapData}
                pagination={false}
                columns={[
                  {
                    title: 'Skill / Technology',
                    dataIndex: 'skill',
                    key: 'skill',
                    render: (text) => <Text strong className={styles.tableSkillFont}>{text}</Text>,
                  },
                  {
                    title: 'Proficiency Level',
                    dataIndex: 'proficiency',
                    key: 'proficiency',
                  },
                  {
                    title: 'Market Demand',
                    dataIndex: 'demand',
                    key: 'demand',
                    render: (demand) => (
                      <Tag color={demand === 'Very High' ? 'red' : 'blue'}>{demand}</Tag>
                    ),
                  },
                  {
                    title: 'Status',
                    dataIndex: 'status',
                    key: 'status',
                    render: (status) => (
                      <Tag color={status === 'Ready' ? 'green' : 'gold'}>{status}</Tag>
                    ),
                  },
                ]}
              />
            </Card>
          </Col>

          {/* AI Recommendations */}
          <Col xs={24} lg={8}>
            <Card
              title={
                <Space>
                  <BulbOutlined className={styles.iconWarning} />
                  <span>Scout Action Items</span>
                </Space>
              }
              className={styles.cardRounded}
            >
              <List
                dataSource={[
                  {
                    title: 'Add GraphQL & Apollo Examples',
                    desc: 'Adding 1 GraphQL endpoint demo can increase your match score for Lead Roles by +6%.',
                  },
                  {
                    title: 'Highlight AntD SSR Optimization',
                    desc: 'Mentioning @ant-design/nextjs-registry in your bio sets you apart in SSR-focused teams.',
                  },
                  {
                    title: 'System Design Preparation',
                    desc: 'Review TypeORM caching and SQLite connection pooling for upcoming technical interviews.',
                  },
                ]}
                renderItem={(item) => (
                  <List.Item className={styles.actionItem}>
                    <Space align="start">
                      <BookOutlined className={styles.bookIcon} />
                      <div>
                        <Text strong className={styles.actionTitle}>
                          {item.title}
                        </Text>
                        <Text type="secondary" className={styles.actionDesc}>
                          {item.desc}
                        </Text>
                      </div>
                    </Space>
                  </List.Item>
                )}
              />
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  );
}
